### ISSUE TITLE
How to include metaparsedown?

### ISSUE THREAD

**Issue by marcobambini** [pagerange/metaparsedown#1]
I am sure I am missing something obvious but I need help in setting up the initial include.
My directory looks like:

- test.php
- MetaParsedown.php
- Parsedown.php
- ParserNotFoundException.php
- Parsers
  - ParserInterface.php
  - YamlParser.php

in test.php I wrote:
```
include_once("Parsedown.php");
include_once("MetaParsedown.php");
```

but I received the following error:
**Fatal error: Interface 'Pagerange\Markdown\Parsers\ParserInterface' not found in path/to/MetaParsedown.php**

How can I use MetaParsedown in my test.php file?

**Comment by IJIJI** [comment]
How'd you solve this?

**Comment by pagerange** [comment]
You are using the version of MetaParsedown that requires Composer to install.  Use the no-composer version instead:

https://github.com/pagerange/metaparsedown_no_composer

**Comment by IJIJI** [comment]
Ahh I see
